# Generated by Django 3.2.6 on 2021-10-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='pic'),
        ),
    ]
