# Generated by Django 3.2.6 on 2021-10-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_itemmodel_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='quality',
            field=models.IntegerField(choices=[(0, 'low'), (1, 'normal'), (2, 'high')], default=1, null=True),
        ),
    ]
