# Generated by Django 3.2.6 on 2021-10-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_itemmodel_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='item_Price',
            field=models.IntegerField(default=100),
        ),
    ]
