# Generated by Django 3.2.6 on 2021-10-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_itemmodel_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='item_offer',
            field=models.IntegerField(default=0),
        ),
    ]
