# Generated by Django 3.2.6 on 2021-11-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_itemmodel_item_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to='pic'),
        ),
    ]
