# Generated by Django 3.2.6 on 2021-11-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211121_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_item_quality',
            field=models.IntegerField(default=0),
        ),
    ]
