# Generated by Django 3.2.6 on 2021-11-21 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_alter_cart_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_user',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
