# Generated by Django 3.2.6 on 2021-11-22 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0011_auto_20211121_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_user',
        ),
        migrations.CreateModel(
            name='CartUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.cartuser'),
            preserve_default=False,
        ),
    ]
