# Generated by Django 3.2.6 on 2021-11-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20211122_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oder_user', models.CharField(max_length=256)),
                ('mobile_no', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('country', models.CharField(max_length=256)),
                ('Address', models.CharField(max_length=500)),
                ('Landmark', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
            ],
        ),
    ]
