# Generated by Django 3.2.6 on 2021-11-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_oders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oders',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='oders',
            old_name='Landmark',
            new_name='landmark',
        ),
    ]
